name: "test"
on:
  pull_request:
  push:
    branches:
      - 'master'

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v24
      - name: "Run tests"
        run: 'nix flake check --print-build-logs --keep-going'
